// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLqfDheFxMG2bBUs8pa_E7XsWvhRRfBU',
    appId: '1:609217950576:web:f624366b16ab64045ed5b5',
    messagingSenderId: '609217950576',
    projectId: 'loveosapp',
    authDomain: 'loveosapp.firebaseapp.com',
    storageBucket: 'loveosapp.firebasestorage.app',
    measurementId: 'G-1GN0NEZFHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtnF9b4-IbnYNR9e4u-1G-67Dr50DtFd0',
    appId: '1:609217950576:android:8b4faaa2d1636c795ed5b5',
    messagingSenderId: '609217950576',
    projectId: 'loveosapp',
    storageBucket: 'loveosapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66ZbaJir066qsN5G0hdNTvcF2jgLlPNA',
    appId: '1:609217950576:ios:f47163976009c7695ed5b5',
    messagingSenderId: '609217950576',
    projectId: 'loveosapp',
    storageBucket: 'loveosapp.firebasestorage.app',
    iosBundleId: 'com.example.chaosEngine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66ZbaJir066qsN5G0hdNTvcF2jgLlPNA',
    appId: '1:609217950576:ios:f47163976009c7695ed5b5',
    messagingSenderId: '609217950576',
    projectId: 'loveosapp',
    storageBucket: 'loveosapp.firebasestorage.app',
    iosBundleId: 'com.example.chaosEngine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLqfDheFxMG2bBUs8pa_E7XsWvhRRfBU',
    appId: '1:609217950576:web:ecce9ea6cb7ce8275ed5b5',
    messagingSenderId: '609217950576',
    projectId: 'loveosapp',
    authDomain: 'loveosapp.firebaseapp.com',
    storageBucket: 'loveosapp.firebasestorage.app',
    measurementId: 'G-TLLK4FMQ2Z',
  );
}
